### ISSUE TITLE
Document getting started with Maven in more detail

### ISSUE THREAD

**Issue by filmaj** [slackapi/java-slack-sdk#988]
First, forgive me for the really basic questions as it has been a million years since I've worked with Java projects and am a java noob 😅  I think some possibly basic maven setup information is missing in this guide, hopefully the information here can help figure that out, and I will happily update the getting started guides to be more total-java-noob friendly.

I tried following the getting started guides on the bolt docs (in particular, the [Socket Mode Getting Started Guide](https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt-socket-mode)), but got stuck pretty quickly.

First in the "Project Setup" section:

> After you create your Maven project

There is nothing linked here, so I googled and followed the [Maven quickstart instructions](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html). I was able to create a maven project using `mvn generate` and then compile the basic project using `mvn package`. Finally, I could run the built project using `java -cp` - so I thought I was ok.

Next I added the dependencies listed under the Maven section of Project Setup of the Bolt Getting Started Guide. However, the last note in this section confused me:

> If you use Java-WebSocket library, add the artifact instead of tyrus-standalone-client.

I don't know if I'm using Java-WebSocket or not by default, so I don't know if I should add the relevant artifact and remove the tyrus-standalone-client 🤷 ❓ 

Next I moved on to the "Run Your Bolt App in 3 Minutes" section of the getting started guide. However, there is no Maven-specific instructions here - only instructions for changing a build.gradle file - so I skipped to copying the code for MyApp.java into my maven project.

Next section I moved to is "Start the App with Two Env Variables". I set the two environment variables, but the running instructions here are again gradle-specific and nothing Maven-specific. So I assumed the same package and running instructions relevant to the maven quickstart applied. However, running `mvn package` with the basic socket mode app code in place yields:

```
12:05:12 in ~/src/slapp-BoltJavaApp
➜ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< ca.filmaj.boltjavaapp:boltjavaapp >------------------
[INFO] Building boltjavaapp 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ boltjavaapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/fmaj/src/slapp-BoltJavaApp/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ boltjavaapp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/fmaj/src/slapp-BoltJavaApp/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/fmaj/src/slapp-BoltJavaApp/src/main/java/ca/filmaj/boltjavaapp/MyApp.java:[11,38] lambda expressions are not supported in -source 7
  (use -source 8 or higher to enable lambda expressions)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.784 s
[INFO] Finished at: 2022-05-20T12:05:17-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project boltjavaapp: Compilation failure
[ERROR] /Users/fmaj/src/slapp-BoltJavaApp/src/main/java/ca/filmaj/boltjavaapp/MyApp.java:[11,38] lambda expressions are not supported in -source 7
[ERROR]   (use -source 8 or higher to enable lambda expressions)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### The page URLs

* https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt-socket-mode

### More Context

My mvn and java versions:

```
➜ mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /usr/local/Cellar/maven/3.8.5/libexec
Java version: 11.0.15, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.15/libexec/openjdk.jdk/Contents/Home
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "12.3.1", arch: "x86_64", family: "mac"
```

**Comment by seratch** [comment]
@filmaj Thanks for this feedback! 

First of all, my basic stance is that **this document is not for Java beginners but for Java developers that would like to know how to use this SDK**. For this reason, I believe that it's fine to skip some very details. That being said, I agree that it would be great if we make the documents even more friendly.

>However, the last note in this section confused me:
>If you use Java-WebSocket library, add the artifact instead of tyrus-standalone-client.
>I don't know if I'm using Java-WebSocket or not by default, so I don't know if I should add the relevant artifact and remove the tyrus-standalone-client 🤷 ❓

Both Tyrus and Java-WebSocket are optional dependencies of slack-api-package / bolt-socket-mode. The default recommendation is Tyrus as it is the reference implementation of the standard WebSocket client spec in Java. However, some developers may prefer using the alternative: Java-WebSocket. That's the case here. I agree that the part can be clearer.  Can you send a pull request for it?

>Next I moved on to the "Run Your Bolt App in 3 Minutes" section of the getting started guide. However, there is no Maven-specific instructions here - only instructions for changing a build.gradle file

Do you mean that we should add pom.xml part here? The document already mentioned how to configure a project with Maven in the previous "Project Setup" part. For this reason, I didn't repeat the same thing. If you think that this is not developer-friendly (frankly, I don't think so), we can add the dependencies part to the section as an improvement.

> - so I skipped to copying the code for MyApp.java into my maven project.

I don't think that majority of Maven developers won't be confused here but it's fine to make the part more friendly by adding pom.xml example or saying that "Of course, you can use Maven for setting this project up!".

>[ERROR] /Users/fmaj/src/slapp-BoltJavaApp/src/main/java/ca/filmaj/boltjavaapp/MyApp.java:[11,38] lambda expressions are not supported in -source 7 (use -source 8 or higher to enable lambda expressions)

Your build settings force the compilation with Java 1.7. It's a common practice to set source / target language version: https://github.com/slackapi/java-slack-sdk/blob/v1.22.1/pom.xml#L44-L45

This is not specific to this SDK at all but if you think that we should tell this to the document visitors to make the documents even more inclusive, it would be okay to add an extra sentence about this.

I do understand that some things might be confusing to you. If you are keen to make our documents even more friendly to everyone (beyond the common expectations to SDK docs), I am happy to work with you on updating the documents.

**Comment by filmaj** [comment]
I defer to your opinion on what should be included or not @seratch as you have the most context/experience in this project. I will definitely send a PR with my suggestions and based on your comments so far! I don't want to go too overboard and hand-hold on every little thing, but I'd like to think I'm an experienced developer - even though I haven't touched Java development in probably 7 years - so I have a vague familiarity with maven and gradle. I was able to get a gradle-based Bolt project set up and running quickly without issue but failed with maven. So even just adding the tiny hints to unblock unfamiliar developers might be better than nothing.

We can discuss the details in the PR I will open and we can include or not include any of my proposed changes based on your feedback 🙇

**Comment by filmaj** [comment]
Working on a PR for this... @seratch I have another dumb question for you: how do I run the basic Bolt for Java socket mode app using maven? I can `mvn compile package` to compile into a .jar now after updating the compiler source/target to 1.8. But I am still a stuck 🙈 

I tried more explicitly configuring the maven jar plugin in my `pom.xml` to point to the entrypoint for the app:

```
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-jar-plugin</artifactId>
		<version>3.1.0</version>
		<configuration>
			<archive>
				<manifest>
					<addClasspath>true</addClasspath>
					<mainClass>ca.filmaj.boltjavaapp.MyApp</mainClass>
				</manifest>
			</archive>
		</configuration>
```

and here's my app:

```
13:38:53 in ~/src/slapp-BoltJavaMavenApp
➜ cat src/main/java/ca/filmaj/boltjavaapp/MyApp.java
package ca.filmaj.boltjavaapp;

import com.slack.api.bolt.App;
import com.slack.api.bolt.socket_mode.SocketModeApp;

public class MyApp {
  public static void main(String[] args) throws Exception {
    // App expects an env variable: SLACK_BOT_TOKEN
    App app = new App();

    app.command("/hello", (req, ctx) -> {
      return ctx.ack(":wave: Hello!");
    });

    // SocketModeApp expects an env variable: SLACK_APP_TOKEN
    new SocketModeApp(app).start();
  }
}
```

But trying to run it via `java -jar` I still get errors around class path for bolt not being able to be found:

```
13:39:11 in ~/src/slapp-BoltJavaMavenApp
➜ java -jar target/boltjavaapp-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/slack/api/bolt/App
	at ca.filmaj.boltjavaapp.MyApp.main(MyApp.java:9)
Caused by: java.lang.ClassNotFoundException: com.slack.api.bolt.App
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

I'm sure this is super basic stuff, sorry for the dumb question. I tried googling it for a bit but didn't get anywhere...

**Comment by seratch** [comment]
@filmaj This is an answer for you. This could be a yet another confusing part of Maven: https://github.com/slackapi/java-slack-sdk/issues/107#issuecomment-473527413

**Comment by seratch** [comment]
@filmaj by the way, if your goal is just to run the main method from your terminal console, this command would be the most common way to do so: https://www.baeldung.com/maven-java-main-method Also, I always run a main method using IDE (IntelliJ IDEA).

**Comment by filmaj** [comment]
`mvn compile exec:java -Dexec.mainClass="ca.filmaj.boltjavaapp.MyApp"` is what I wanted! Alright!

One last question (I promise): when I run the above, I see this as the last output in my terminal:

```
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ boltjavaapp ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I think these errors around SLF4J is maybe why I don't see any logging from the Bolt side? If I manually add a `System.out.print()` line to my main class, then it shows up in the output. but for example, compared to the basic Gradle app, that app does show some amount of standardized logging in the output:

```
➜ gradle run -DslackLogLevel=debug

> Task :app:run
[Grizzly(2)] INFO com.slack.api.socket_mode.SocketModeClient - New session is open (session id: 4ff6cdac-4dbe-4e58-a9cb-d36f1c0ab3d6)
<=========----> 75% EXECUTING [12s]
> :app:run
```

One extra note about the gradle output above, it does not seem like the `slackLogLevel=debug` flag passed to `gradle run` creates any additional debug logging - not sure if that is a bug or something. I tried searching through the codebase for `slackLogLevel` but nothing showed up other than in the docs.

**Comment by filmaj** [comment]
Ahh, regarding the SLF4J error, I think the getting started guide was missing adding the dependency. After I added the following to my `pom.xml`, the error went away and I see more proper logging now:

```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.7.36</version>
    </dependency>
```

**Comment by filmaj** [comment]
> One extra note about the gradle output above, it does not seem like the slackLogLevel=debug flag passed to gradle run creates any additional debug logging - not sure if that is a bug or something. I tried searching through the codebase for slackLogLevel but nothing showed up other than in the docs.

My bad, I missed the extra configuration step in `build.gradle` for setting up the run task that maps the debug logging flag to the correct property. Once I added this to my `build.gradle`, things worked fine:

```
run {
    // gradle run -DslackLogLevel=debug
    systemProperty "org.slf4j.simpleLogger.log.com.slack.api", System.getProperty("slackLogLevel")
}
```
