### ISSUE TITLE
[micronaut-bolt] Error when add dependency on Micronaut 2.1.1

### ISSUE THREAD

**Issue by brunodomenici** [slackapi/java-slack-sdk#712]
Hi,

Is `micronaut-bolt` compatible with Micronaut 2.1.1?
I've tried to add the dependency in my existing project and I got an exception o application start-up:

```
Error starting Micronaut server: Error loading service [com.slack.api.bolt.micronaut.$SlackAppControllerDefinitionClass]: io.micronaut.inject.annotation.DefaultAnnotationMetadata.<init>(Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Z)V
```
Dependency
```
    <dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-micronaut</artifactId>
      <version>1.7.0</version>
    </dependency>
```

#### The Slack SDK version

```
[INFO] \- com.slack.api:bolt-micronaut:jar:1.7.0:compile
[INFO]    +- com.slack.api:slack-api-model:jar:1.7.0:compile
[INFO]    +- com.slack.api:slack-api-client:jar:1.7.0:compile
[INFO]    +- com.slack.api:slack-app-backend:jar:1.7.0:compile
[INFO]    \- com.slack.api:bolt:jar:1.7.0:compile
[INFO] |  \- com.slack.api:bolt-micronaut:jar:1.7.0:compile
[INFO] |     +- com.slack.api:slack-api-model:jar:1.7.0:compile
[INFO] |     +- com.slack.api:slack-api-client:jar:1.7.0:compile
[INFO] |     +- com.slack.api:slack-app-backend:jar:1.7.0:compile
[INFO] |     \- com.slack.api:bolt:jar:1.7.0:compile
```

#### Java Runtime version

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

#### OS info

```
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H524
Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
```

#### Actual result:

StackTrace:
```
18:43:07.594 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [override]
18:48:00.198 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error loading service [com.slack.api.bolt.micronaut.$SlackAppControllerDefinitionClass]: io.micronaut.inject.annotation.DefaultAnnotationMetadata.<init>(Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Z)V
java.util.ServiceConfigurationError: Error loading service [com.slack.api.bolt.micronaut.$SlackAppControllerDefinitionClass]: io.micronaut.inject.annotation.DefaultAnnotationMetadata.<init>(Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Z)V
	at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0(DefaultServiceDefinition.java:71)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.micronaut.core.io.service.DefaultServiceDefinition.load(DefaultServiceDefinition.java:67)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoSuchMethodError: io.micronaut.inject.annotation.DefaultAnnotationMetadata.<init>(Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Z)V
	at com.slack.api.bolt.micronaut.$SlackAppControllerDefinitionClass.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0(DefaultServiceDefinition.java:69)
	... 17 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:63116', transport: 'socket'
```

**Comment by seratch** [comment]
Hi @brunodomenici , thanks for using the Bolt adapter for Micronaut!

>Is micronaut-bolt compatible with Micronaut 2.1.1?

No, it isn't. It compiles with the latest version - v2.4 as of today. https://github.com/slackapi/java-slack-sdk/blob/v1.7.0/bolt-micronaut/pom.xml#L13

Generally speaking, I recommend upgrading to the latest minor version. If you have reasons to keep using the old version, please consider copying [these classes](https://github.com/slackapi/java-slack-sdk/tree/v1.7.0/bolt-micronaut/src/main/java/com/slack/api/bolt/micronaut) and modifying them in your app. As you can see, it's a pretty small and manageable module.

**Comment by brunodomenici** [comment]
I've upgraded and it works, thanks @seratch
